CREATE TABLE detalle (
  id          NUMBER GENERATED ALWAYS AS IDENTITY,
  nombre_detalle    VARCHAR2(50) NOT NULL,
  fecha_creacion    DATE DEFAULT SYSDATE,
  fecha_modificacion    DATE DEFAULT SYSDATE,
  CONSTRAINT detalle_pk PRIMARY KEY (id)
);

CREATE TABLE marca (
    id NUMBER GENERATED ALWAYS AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    fecha_creacion DATE DEFAULT SYSDATE,
    fecha_modificacion DATE DEFAULT SYSDATE,
    PRIMARY KEY (id)
);

CREATE TABLE lugar_creacion (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    direccion VARCHAR2(255) NOT NULL,
    canton VARCHAR2(100) NOT NULL,
    fecha_creacion DATE DEFAULT SYSDATE NOT NULL,
    fecha_modificacion DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE producto (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_detalle NUMBER NOT NULL,
  id_marca NUMBER NOT NULL,
  id_lugar_creacion NUMBER NOT NULL,
  nombre VARCHAR2(100) NOT NULL,
  precio NUMBER(10,2) NOT NULL,
  peso NUMBER(10,2) NOT NULL,
  fecha_vencimiento DATE,
  fecha_creacion DATE DEFAULT SYSDATE NOT NULL,
  fecha_modificacion DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_producto PRIMARY KEY (id),
  CONSTRAINT fk_producto_detalle FOREIGN KEY (id_detalle) REFERENCES detalle(id),
  CONSTRAINT fk_producto_marca FOREIGN KEY (id_marca) REFERENCES marca(id),
  CONSTRAINT fk_producto_lugar_creacion FOREIGN KEY (id_lugar_creacion) REFERENCES lugar_creacion(id)
);


CREATE TABLE tipo_movimiento (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(255),
  fecha_creacion DATE DEFAULT SYSDATE,
  fecha_modificacion DATE DEFAULT SYSDATE
);

CREATE TABLE movimiento (
  id               NUMBER(10)    PRIMARY KEY,
  id_producto      NUMBER(10)    NOT NULL,
  id_tipo_movimiento NUMBER(10)  NOT NULL,
  id_persona       NUMBER(10)    NOT NULL,
  fecha_creacion   DATE          DEFAULT SYSDATE,
  fecha_modificacion DATE       DEFAULT SYSDATE,
  CONSTRAINT fk_movimiento_producto
    FOREIGN KEY (id_producto)
    REFERENCES producto(id),
  CONSTRAINT fk_movimiento_tipo_movimiento
    FOREIGN KEY (id_tipo_movimiento)
    REFERENCES tipo_movimiento(id),
  CONSTRAINT fk_movimiento_persona
    FOREIGN KEY (id_persona)
    REFERENCES persona(id)
);



CREATE TABLE persona (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre VARCHAR2(50) NOT NULL,
  apellidos VARCHAR2(50) NOT NULL,
  correo VARCHAR2(100),
  cedula NUMBER NOT NULL,
  id_tipo_persona NUMBER NOT NULL,
  fecha_creacion DATE DEFAULT SYSDATE,
  fecha_modificacion DATE DEFAULT SYSDATE,
  PRIMARY KEY (id),
  FOREIGN KEY (id_tipo_persona) REFERENCES tipo_persona(id)
);


CREATE TABLE tipo_persona (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  descripcion VARCHAR2(50) NOT NULL,
  fecha_creacion DATE DEFAULT SYSDATE NOT NULL,
  fecha_modificacion DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT tipo_persona_pk PRIMARY KEY (id)
);
